### ISSUE TITLE
panda franka emika real gripper always ends up fully closed using MoveIt

### ISSUE THREAD

**Issue by moucrob** [moucrob/pandaFrankaEmikaGripperBug#1]
@mlautman @davetcoleman Hi, by any chance, you or any other people know why the real panda robot fully closes his gripper if we give too low values here : 
```
void closedGripper(trajectory_msgs::JointTrajectory& posture, double OFFSET_BLACK_GOMUGOMU)
{
  // WOULD BE BETTER TO SET APPLIED FORCE INSTEAD, CHECK LIBFRANKA C++ [TODO]

  double closeSymmetric = 0.025; //[m] how much each finger is shifted from the center

  /* Add both finger joints of panda robot. */
  posture.joint_names.resize(2);
  posture.joint_names[0] = "panda_finger_joint1";
  posture.joint_names[1] = "panda_finger_joint2";

  /* Set them as closed. */
  posture.points.resize(1);
  posture.points[0].positions.resize(2);
  posture.points[0].positions[0] = OFFSET_BLACK_GOMUGOMU/2 + closeSymmetric;
  //OFFSET_BLACK_GOMUGOMU/2 + 0.0095;
  posture.points[0].positions[1] = OFFSET_BLACK_GOMUGOMU/2 + closeSymmetric;
  //OFFSET_BLACK_GOMUGOMU/2 + 0.0095;
  std::cout << "closing = " << 2*posture.points[0].positions[0] << "m" << "\n";
}
```
code part coming from [http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pick_place/pick_place_tutorial.html](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/pick_place/pick_place_tutorial.html)
the full move_group_test.cpp is available in my repositories, panda_ws.

It ends up with the behaviour described onto this gif
![ezgif com-optimize](https://user-images.githubusercontent.com/33000071/43357781-bfac4484-92c1-11e8-91c5-a808e617d8b0.gif)

the standing robot being the real one, stopping its movement after closing its gripper,
 and the moving robot being the simulated one, doing what I want him to do.

**Comment by moucrob** [comment]
Fixed, all the credits go to our engineer.
So for enlarge its inter-fingers width, there was no problem, because we found out that it used the gripper.move() function. But for reduce (grip), it used the gripper.grasp() one, which apparently seems to be buggy currently.

The engineer's (temporary) fix : 

line 51 of /catkin_ws/src/franka_ros/fanka_gripper/src/franka_gripper.cpp, replace this line : 

`if (target_width >= state.width) {`

by this line : 

`if (1 || target_width >= state.width) {`

so that in any case we use the move() function instead of grasp, until it'll be enhanced... (hello panda's control contributors @mlautman @gavanderhoorn @ch1bo @PattexGamer @dudalu @hamid5746 @sgabl @fwalch @christoph-jaehne)

**Comment by davetcoleman** [comment]
glad this was resolved!

**Comment by ch1bo** [comment]
Gripper.grasp() is always fully closing the Franka Hand. The gif indicates you want to only partly close or move the fingers, but without applying a grasping force? If yes, Gripper.move() is the right thing to use!

**Comment by moucrob** [comment]
@ch1bo oh no it'd be great if we could use grasp(), but what happened is that even with something between its fingers, the robot stopped to follow the retreat plan once getting the object grasped (as if its joints were detecting a collision/external force maybe...)
